решена задача 1 модуля sortStrings
js-tasks-ru/js-20220613_eltach00 pull request #2
Opened 2022-06-18 11:44 UTC by Eltach00

2022-06-18 11:45 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-19 12:13 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return (param === 'asc') ? arr.slice().sort((a, b) => a.normalize().localeCompare(b, 'ru', { sensitivity: 'variant', caseFirst: 'upper' } )) :
дубликаты кода следует устранить!

2022-06-19 12:13 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-06-19 13:05 UTC, Eltach00 commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return (param === 'asc') ? arr.slice().sort((a, b) => a.normalize().localeCompare(b, 'ru', { sensitivity: 'variant', caseFirst: 'upper' } )) :
не могу разобраться. Можете, пожалуйста, уточнить. Вы про то, что param по умолчанию 'asc' задается и я  еще в условии проверяю param === 'asc' ?

2022-06-19 14:13 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-19 15:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-06-20 14:56 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +            for (let [key, value] of Object.entries(obj)) {
`const [key, value]`

2022-06-20 14:56 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +            for (let item of fields) {
`const item`

2022-06-20 14:57 UTC, dosandk approved these changes
good 👍

2022-06-20 14:57 UTC, merged

2022-06-20 15:01 UTC, Eltach00 commented
про const понял, учту в дальнейшем, постараюсь не забывать))